/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tencent_angel_graph_model_GraphSage */

#ifndef _Included_com_tencent_angel_graph_model_GraphSage
#define _Included_com_tencent_angel_graph_model_GraphSage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tencent_angel_graph_model_GraphSage
 * Method:    forward
 * Signature: (J[F[F[II[I[I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_tencent_angel_graph_model_GraphSage_forward
  (JNIEnv *, jobject, jlong, jfloatArray, jfloatArray, jintArray, jint, jintArray, jintArray);

/*
 * Class:     com_tencent_angel_graph_model_GraphSage
 * Method:    destroyNetwork
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tencent_angel_graph_model_GraphSage_destroyNetwork
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
